name: appli_scrabble
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  provider: ^6.0.5
  image_picker: ^1.1.2
  image: ^4.5.3
  path_provider: ^2.1.5
  http: ^1.5.0
  opencv_dart: ^1.4.0
  flutter_tesseract_ocr: ^0.4.0  
  archive:
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dictionnaire.txt
    - assets/tessdata/eng.traineddata
    - assets/tessdata_config.json